### ISSUE TITLE
第2章 MAMPインストールの文言がバラバラ

### ISSUE THREAD

**Issue by hamaco** [CI3-guide/preview-book#10]
MAMPインストールの説明部分なのですが、

* クリックしてください
* クリック下さい
* クリックください

と表記が結構バラバラなので統一してあるといいかなって。

あと、Mac の時はダウンロードファイルクリックしてるけど Windows の時はないのかな?

**Comment by rdlabo** [comment]
ありがとうございます。「クリックします」に統一しました。
また、Windowsについてもダウンロードファイルクリックを追加しました！
