### ISSUE TITLE
P28 タイプミスの検知の説明

### ISSUE THREAD

**Issue by hamaco** [CI3-guide/preview-book#15]
> 2.arry_codeというのはおそ らくarray_codeのタイプミスなので緑で誤字の提案をしてくれています。

とありますが、文字色が緑なのと、1つめのメソッド重複の方に合わせて「緑線」とかにした方が良い気がします。

**Comment by rdlabo** [comment]
ありがとうございます。「赤下線」「緑下線」に統一しました！
