### ISSUE TITLE
P67 命名規則の説明が怪しい

### ISSUE THREAD

**Issue by hamaco** [CI3-guide/preview-book#26]
Modelの命名規則に「ハイフンをつけるか」と書いてありますが、そもそもPHPのクラス名にハイフン使えないかと。

**Comment by rdlabo** [comment]
ありがとうございます！以下に表記変更しました。
本当、頭が上がりません・・・。

> 単語の間にはアンダーバー（_）をつけるか単語の最初の文字を大文字にしてつなげて書くかといった違いがあります。
