### ISSUE TITLE
P5 コードの良し悪しの説明が変

### ISSUE THREAD

**Issue by hamaco** [CI3-guide/preview-book#35]
>  最初に、「(プログラミング)コードの良し悪し」について考えてみましょう。  誰にも書けないようなコードを書けるのが良いコードでしょうか。複雑な処理をひとつ ひとつ追っかけて処理していくのがすばらしいプログラマなのでしょうか。

> 誰にも書けないようなコードを書けるのが良いコードでしょうか。

ここ「良いプログラマ」ですか?
ただ、コードの良し悪しなのにプログラマがどうこうってのはなんか説明がおかしい気がするので、ちゃんとコードの説明になるよう文章を直した方が良い気がしました。

**Comment by rdlabo** [comment]
ご指摘の通り、議論が2つに分かれてましたので、コードに集約して以下表記に変更しました。ありがとうございます！

> 　最初に、「（プログラミング）コードの良し悪し」について考えてみましょう。
> 　誰にも書けないようなコードが良いコードでしょうか。他の人が数十行書くコードを複雑怪奇だけどわずか数行にまとめたものが良いコードでしょうか。
> 
> 　そんなことは全くありません。もちろん、凄腕プログラマに分類される人でそういうコードを書く人もいないわけではありませんが、そのコードを「いいコード」と評す人は極小数です。
