### ISSUE TITLE
コラム「PHPコーディング規約」 ：PSRはPHP公式ではありません

### ISSUE THREAD

**Issue by noldor** [CI3-guide/preview-book#37]
> PHP本体がコーディング規約を提供しています。

> PHP公式のコーディング規約は「PSR」と名付けられており、

PSRを定めているPHP-FIGはPHP公式ではありません。もともと「PHP Standards Group」という名前でしたが、誤解を招くということでPHP-FIG（Framework Interoperability Group）という名前になっています。
フレームワーク作者の集まりなので、多くのフレームワークに採用されています。
http://www.php-fig.org/faqs/
よく見るとZend Frameworkも参加しているんですけどね。

残念なことに、CodeIgniterは参加していません。
http://www.php-fig.org/members/

**Comment by kenjis** [comment]
はい、これ非常に問題となりうる誤った解説になってますね。

PHP-FIG自体はPHPのユーザが勝手に集まって作っただけの団体で、
PHP公式ではありません。

あと、FIGを嫌っている人もいます。どんなプロジェクトでも参加
できるわけではなく、参加を拒否されたフレームワークもあります。

**Comment by rdlabo** [comment]
@noldor @kenjis 
こちらご指摘ありがとうございます。完全に勘違いして理解しておりましたので、恥ずかしいばかりです。

> しかしながら、コーディング規約を0からつくるのはとても手間ですので、現場では「Framework Interoperability Group」というグループがつくっているPHP標準コーディング規約「PSR」を使うことが一般的です。

という表記にしました。kenjisさんの「嫌っている人」のご指摘も最もなのですが、規約を持たずに開発している方がターゲット像なので、一例としてご紹介できればと思っておりますー。

ご指摘ありがとうございました！
