### ISSUE TITLE
コラム「PHPコーディング規約」 :TRUE / FALSEは定数にあります

### ISSUE THREAD

**Issue by noldor** [CI3-guide/preview-book#38]
> 特に、真偽を「TRUE」「FALSE」と大文字で書くのは近年のPHPの文化にそぐわず、またPHP本体の定数からも除外されておりますので、

定数から除外、の意味が取れなかったのですが、定義済み定数にTRUE / FALSEは定義されていました。
http://php.net/manual/ja/reserved.constants.php

**Comment by rdlabo** [comment]
あら、どうしてでしょう。

define('TRUE', 2); はエラーは出ずに、define('true', 2); はエラーが出る手元の現象といまいち一致しませんね・・・（私の環境依存なのかな）
といっても、重要な部分ではありませんので

> 特に、真偽を「TRUE」「FALSE」と大文字で書くのは近年のPHPの文化にそぐいませんので、注意が必要です。

に変更しました。ご指摘ありがとうございます！

**Comment by noldor** [comment]
true/falseは大文字小文字を区別しませんので、defineの第3引数を指定してやると、エラーが出ました。
http://php.net/manual/ja/function.define.php
> 注意:
> 大文字小文字を区別しないときは、定数は小文字で格納されます。

```
$ php -v
PHP 7.0.11 (cli) (built: Sep 18 2016 02:45:05) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.11, Copyright (c) 1999-2016, by Zend Technologies
    with Xdebug v2.4.1, Copyright (c) 2002-2016, by Derick Rethans

$ php -r 'define("TRUE", 2, 1);'
PHP Notice:  Constant true already defined in Command line code on line 1
PHP Stack trace:
PHP   1. {main}() Command line code:0
PHP   2. define() Command line code:1
```
