### ISSUE TITLE
8章「脱・Fat Controller」のサンプルコードが何をやりたいのかよくわからない

### ISSUE THREAD

**Issue by noldor** [CI3-guide/preview-book#39]
8章「脱・Fat Controller」のサンプルコードはコントローラで$user配列を作りますが、viewに引き渡さず終了してしまうので何をしたいのかよくわからないです。

また、$userは2～3次元配列のようですが、その配列も何をあらわしているかよくわからないです。
userテーブルの定義が見当たらないというのもありますが、「配列+配列」は配列演算子として有効で、array_merge()とはまた違った動きをします。
http://php.net/manual/ja/language.operators.array.php

**Comment by rdlabo** [comment]
8章はコード例の整理なので、「何をする」はあまり重視していないのですが、少し見当させてくださいませ。

こちら、配列+配列はさすがに筋が悪いということになりまして、変更いたしました。ご指摘ありがとうございますー！。
