### ISSUE TITLE
9章のうち「Viewを分割して使いまわせるように」のHTMLが文法ミス？　だったはず

### ISSUE THREAD

**Issue by noldor** [CI3-guide/preview-book#41]
P75 コード例
```
<!̶ application/views/common/header.php ̶>

<!DOCTYPE html>
<html lang="ja"> 
```

DOCTYPE宣言前にコメントは文法ミスだったかと思います。ちょっと裏が取れなかったので、間違っていたらすみません。

**Comment by rdlabo** [comment]
こちら、確かIE6あたりでうまく認識しなかった問題であり、文法ミスではなかったと記憶しておりますー。また、これを写経しろというよりガイド的役割（けど、まるまる写経しそうな人がいるのでコメントアウトしてる）ですので、こちらはそのまま残させていただきますー。
ご指摘ありがとうございました！
