### ISSUE TITLE
コラム「バージョン管理をしよう」：gitlab.comはいかがでしょうか

### ISSUE THREAD

**Issue by noldor** [CI3-guide/preview-book#43]
gitのサービスとしてオープンなgithub、クローズドなbitbucketという感じで紹介されていますが、gitlabはいかがでしょうか？
もはや「貧者のgithub enterprise」とは言えないほと機能盛りだくさんですし、webサービスとしても提供されています。1リポジトリ10GBまでですが参加人数無制限、個数無制限でクローズドリポジトリを作れます。
https://about.gitlab.com/gitlab-com/

……英語だから避けた、でしょうか。

**Comment by rdlabo** [comment]
こちら、いまいちgitlabのいい書籍がなかったんですよね・・・。
初心者にとってgitはまるまる新たな言語を覚えるのに等しいわけですので、できればサイトへの誘導ではなく、入門書的なものを提示したいと思いまして割愛させていただいておりますー。

**Comment by noldor** [comment]
なるほど、承知しました。確かにこれという本はないですね。
