### ISSUE TITLE
１章冒頭のベネッセ事件についての言及

### ISSUE THREAD

**Issue by ayato-git** [CI3-guide/preview-book#44]
preview-book、ありがたく読ませて頂いてます。

p.5の「セキュリティリスクには細心の注意を払う必要があります」の部分ですが、
ベネッセの事件は名簿持ち出しによるソーシャルエンジニアリングに類する事件なので、
「プログラマの義務として一般的に認識」される例としては少しズレがありそうです。

IPAや徳丸本等で言及されている、以下の例を使うのはどうでしょうか？
[ SQLインジェクション対策もれの責任を開発会社に問う判決 ](http://blog.tokumaru.org/2015/01/sql.html)

**Comment by rdlabo** [comment]
ご指摘、ありがとうございます！
サービスで得た個人情報の管理話で一番に思いついた事件だったのですが、たしかにプログラミングとの関係性は薄いので、いただいた事例に差し替えさせていただきました！
