### ISSUE TITLE
２章 MAMPのインストールの表記

### ISSUE THREAD

**Issue by ayato-git** [CI3-guide/preview-book#45]
優先度低めです。

p.10 にて、

    2. このインストーラーによって、『Macのアプリケーションフォルダの中に、「MAMP」 と「MAMP PRO」というフォルダができるけど

となっていて、この部分だけがですます調から口語調になっていて、
少し不自然かと思いました。

**Comment by rdlabo** [comment]
説明自体も冗長だったので

> このインストーラーによって、『アプリケーションフォルダに生成される「MAMP」と「MAMP PRO」というフォルダを削除したり名前の変更をしないように』と案内がでます。「続ける」をクリックします。

に変更させていただきました。ご指摘ありがとうございます！
