### ISSUE TITLE
2章 Composerのインストール

### ISSUE THREAD

**Issue by ayato-git** [CI3-guide/preview-book#46]
# 「Mac OSの場合」

コード部分がいきなり

```sh
$ php composer-setup.php --install-dir=bin --filename=composer
```

から始まっていますが、
いきなり `composer-setup.php` を叩くのは
その前のMAMPのインストール紹介に比べると丁寧さの乖離があると思います。
（composer-setup.phpってどこにあるの？となりそうです。）

[Composer公式のダウンロードガイド](https://getcomposer.org/download/)
に準ずる形が無難ではないでしょうか。

また、その前の

    パッケージインストールに利用されるようになりました(2015年 現在)

は意図的に2015年ですか？

**Comment by ayato-git** [comment]
また、 p.16 では
    WIndowsの場合は
 と入力して、

**Comment by ayato-git** [comment]
また、 p.16 では

    WIndowsの場合は
    $ cd C:¥MAMP/htdocs
    と入力して、

と、区切り文字が混在しています。

**Comment by rdlabo** [comment]
あら、書いた解説の部分、一部ごっそり消えてますね。ご指摘ありがとうございます、加筆します！！
また、2016年に直します。私が書き始めたのが2015年でそれがまだ残ってる・・・。

また、こちら、手元で

`C:/MAMP/htdocs`

に修正しました！丁寧にレビューいただきまして、本当にありがとうございます！！
