### ISSUE TITLE
Modelのconstructorについて

### ISSUE THREAD

**Issue by nanndemoiikara** [CI3-guide/preview-book#47]
P51

```book
「parent::__construct()」は、Modelの様々な機能を呼び出している処理で、
```

CI_Modelで呼び出しているのはlog_message関数だけです。
書かなくてもマジックメソッドでCI_Controllerを呼び出し動作します。

https://github.com/bcit-ci/CodeIgniter/blob/develop/system/core/Model.php#L56

**Comment by rdlabo** [comment]
こちら、ご指摘ありがとうございます。
本当ですね、どこで記憶違いをしていたのか。。。てっきり間違ったままだすところでした。ご指摘ありがとうございます！！
