### ISSUE TITLE
result_arrayについて

### ISSUE THREAD

**Issue by nanndemoiikara** [CI3-guide/preview-book#48]
P52

result_arrayの判定部分、判定せずとも0件の場合は空の配列が返るかと思われます。

https://github.com/bcit-ci/CodeIgniter/blob/a4ed425b218942ed7e60d993325f592f5c24e59e/system/database/DB_result.php#L276

**Comment by rdlabo** [comment]
ご指摘ありがとうございます。
こちら、本書では連想配列で返してますが、falseで返したり、更に呼び出し処理をする時のヒントで条件分岐をかけております。

とはいえ、それも言われないとわからないですね。本文に

> （0行で「$query->result_array()」を返した場合も空の配列が返されますので、この条件分岐は省略可能です）

との注釈を挿入しました。ご指摘ありがとうございます！
