### ISSUE TITLE
POSTリクエストの判定

### ISSUE THREAD

**Issue by nanndemoiikara** [CI3-guide/preview-book#49]
P56

```book
「$this->input->post()」でPOST処理の有無を確認して
```

post結果を全て取得するより
Inputクラスのmethodを使用し判定した方が良いかと思われます。

```book
if ( 'POST' === $this->input->method('TRUE') )
```

これはPOSTリクエストのデータがあるかでは無く、
POSTリクエストであるという意味で判定する為です。

https://www.codeigniter.com/user_guide/libraries/input.html#CI_Input::method

**Comment by rdlabo** [comment]
ご指摘ありがとうございます。また確認が取れ次第、反映させていただきます！！

**Comment by rdlabo** [comment]
こちら、中で議論したのですが、

・テストの関係で$_POSTに直接データつっこむ場合、判定ができない
・読者は$this->input->methodを覚えてもここでしか使わない

という問題を整理しまして、注釈でご指摘の処理の方法を紹介させていただくことにしましたー。
ご指摘ありがとうございました！
