### ISSUE TITLE
sublime textはIDEなのか

### ISSUE THREAD

**Issue by noldor** [CI3-guide/preview-book#5]
IDEとは何なのか、という話にもなってしまいそうですが、
sublime textはIDEではなくエディタを名乗っているように思います。
https://www.sublimetext.com/

タイトルを変えるとかで対応でしょうか。

**Comment by rdlabo** [comment]
sublimeは実質パッケージでIDEになりますしね・・・。
タイトルで「エディタ」といいだすと、エディタ間の機能比較話になってしまうので

> 国内でも多くのファンがいるSublime Text。「テキストエディタ」を名乗っておりますが、IDEといって遜色がない機能を提供しています。

という表記で対応いたしました。ご指摘ありがとうございます！
