### ISSUE TITLE
configファイルのロードの記述に関して

### ISSUE THREAD

**Issue by 46-96** [CI3-guide/preview-book#50]
70ページ
$this->load->config(‘per’); 
これはこれで動作するが
ドキュメント上は
$this->config->load(‘per’); 
となっている。

超入門ということなので、公式ドキュメントとあわせるか説明があったほうがいいかも。
クラスリファレンスには書かれているけど
ドキュメントの例もloadを前の方に変更してほしいところですけどね

**Comment by rdlabo** [comment]
こちら、公式ドキュメントが変ですね・・・。
脚注つけます。ありがとうございます！
