### ISSUE TITLE
typo(コラム「PHPコーディング規約」)

### ISSUE THREAD

**Issue by noldor** [CI3-guide/preview-book#7]
P39
> true,falseは小文字で表記しなければなりません

CodeIgniterのPHP スタイルガイドではTRUE/FALSEは大文字指定です。

http://codeigniter.jp/user_guide/3/general/styleguide.html#true-false-null
> TRUE 、 FALSE および NULL キーワードは常にすべて 大文字にすべきです。

ただし、このPHPスタイルガイドはCI本体へのコントリビュータへの要請事項なので、ユーザにはどうなのよと思うところでもあります（PSRではtrue/false/nullは小文字指定）。別途起票します。

P39
> 定数（DEFINR）は全て大文字で書き

DEFINE、でしょうか。

P40
> 最初意外の単語意外を大文字からはじめる

最初の単語以外
（※意外が2つダブっているのと、誤字）

P40
>単語をアンダーバーで区切るアンダースコア（get_user_data）のどれかで

・「アンダースコア」を削除
・「アンダーバー」を削除し、「アンダースコア」を削除したアンダーバーの位置に移動
のどちらか。

**Comment by rdlabo** [comment]
CIのスタイルガイドは別Issueにコメントします。
typoありがとうございます。また、アンダースコアは書き方だったのですがわかりにくいのでスネークケースに変更しました！
