### ISSUE TITLE
コラム「PHPコーディング規約」 にphp-cs-fixerを追加してはどうでしょう

### ISSUE THREAD

**Issue by noldor** [CI3-guide/preview-book#8]
「PHPコーディング規約」 にはPSRの紹介がありますが、php-cs-fixerでpsr準拠のコードに自動修正することができます。go言語でいうところのgofmtにあたります。

http://cs.sensiolabs.org/

psrを定めているPHP-FIGのメンバーでもあるFabienが作っているので、PHP-FIG準公式みたいな位置づけだと思っています（未確認）。

コマンドライン実行がいるので入門書にはちょっとどうかなとは思うのですが、composerを紹介しているなどあるので、これも紹介すると良いのではないかと思います。

こんな感じで使います。
https://blog.noldor.info/2016/07/php-cs-fixer-config-for-codeigniter3

**Comment by rdlabo** [comment]
一部のpsrのみ適応というのはちょっと重いですね・・・。
こちらのブログをそのまま紹介させていただいて、このように準拠を確認する方法がある、という表記の仕方をしてもよろしいでしょうかー？？

**Comment by noldor** [comment]
はい、大丈夫です。
確かにpsr-0だけ省略はちょっと入門向けではない判断が入ってしまうので、全体的なバランス考えて書きにくいようであれば単に提案却下で省略なさってください。

**Comment by rdlabo** [comment]
全体的に入門的というかPHP書き始めで、自動修正はハイレベルだなという結論になりました。発展編などでは確かに重要な要素だと思います。ありがとうございました！
