### ISSUE TITLE
コラム「PHPコーディング規約」 のCodeIgniter PHPスタイルガイドの紹介が誤解を招きそう

### ISSUE THREAD

**Issue by noldor** [CI3-guide/preview-book#9]
http://codeigniter.jp/user_guide/3/general/styleguide.html

PHPスタイルガイドの位置づけは
　・CodeIgniterのコントリビュータへの要請事項
　・ユーザにも「推奨はしている」
という扱いなのですが、[論理演算子](http://codeigniter.jp/user_guide/3/general/styleguide.html#id8)で「OR」と「&&」を推奨するなど、ちょっとどうなのよと思う点がそこかしこにあります。

さらにはPSRと矛盾する事項もちらほらあり、PSRと同じ位置づけで並べて紹介するのはかえって混乱を招くのではないかと思います。

CodeIgniter PHPスタイルガイドの立脚点が「劣悪な開発環境でも間違えないように」というところにあると思うのですが、IDEを勧める本書ではふさわしくなく、どちらかを選ぶならPSRを推したいです。CodeIgniter PHPスタイルガイドはもっと踏み込むか、バッサリ「お勧めしない」で切り捨てたほうが良いと思います。

**Comment by rdlabo** [comment]
ですね。よく考えると、TRUEなど本書とも衝突する規約がありますので、ばっさり切り捨てるようにいたしますー！
